language: python
python:
  - "2.7"

# command to install dependencies
install:
	- pip install pytest
	- pip install mongomock
  - pip install coverage
  - python setup.py install

# command to run tests
script: py.test --cov=rvo

# Codecov.io integration
before_install:
  - pip install codecov

after_success:
  - codecov
