language: python
python:
- "2.7"

# command to install dependencies
install:
  - pip install .
  - python -c 'import nltk; nltk.download("book")'

# command to run tests
script: PYTHONPATH=. py.test --cov=rvo

# Codecov.io integration
before_install:
  - pip install codecov
  - pip install pytest
  - pip install mongomock
  - pip install coverage
  - pip install pytest-cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
